### ISSUE TITLE
Promisified function can recieve more than two arguments

### ISSUE THREAD

**Issue by jifeon** [dfilatov/vow-node#3]
From [node docs](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback):

```
child_process.exec(command[, options], callback)

callback Function called with the output when process terminates
    error Error
    stdout Buffer
    stderr Buffer
```

Now I can't use vow-node with exec because

``` js
vowNode.invoke(exec, command).then(function (stdout, stderr) {
  typeof stderr === 'undefined';
});
```

**Comment by jifeon** [comment]
Just realized that callback inside `then` cannot receive more than one argument. It would be great if some method exists, like `invoke`, but resolving an array to use spread after it.

**Comment by dfilatov** [comment]
Since 0.3.0 invoke/promisify can work with such functions:
```js
vowNode.invoke(exec, command).then(function (stdout, stderr) {
  typeof stderr !== 'undefined';
});
```

**Comment by jifeon** [comment]
thanks!
